#!/usr/bin/env bash

aux_port=${AUX_PORT:-9090}

if [ -z "$NGROK_API_TOKEN" ]; then
  NGROK_OPTS="${NGROK_OPTS} -authtoken ${NGROK_API_TOKEN}"
fi

# Start the TCP tunnel
ngrok_cmd=".heroku/bin/ngrok ${NGROK_COMMAND:-"http"} -log stdout --log-level debug ${NGROK_OPTS} ${aux_port}"
echo "Starting ngrok..."
eval "$ngrok_cmd &"
ngrok_pid=$!

eval "$@"
